"Raj":
  "entries": 1
"Jay":
  "entries": 1
"Jash":
  "entries": 1
"Mausmi":
  "entries": 1
"Akash":
  "entries": 1
"Jinali":
  "entries": 1
"Dipal":
  "entries": 1
"Ron":
  "entries": 1
"Nakul":
  "entries": 1
"Disha":
  "entries": 1
"Munindra":
  "entries": 1
"Viral":
  "entries": 1
"Neeti":
  "entries": 1
"Khush":
  "entries": 1
"Dhaval":
  "entries": 1
"Mudra":
  "entries": 0
"Juhi":
  "entries": 1
